### PR TITLE
login, signup and password page added

### PR DESCRIPTION
**Pull request by vaibhav18matere**
Preview link : https://flamboyant-tesla-60f5a8.netlify.app

### CODE REVIEW

**Review by harshkotkar5557 — APPROVED** [review]
Looks good to me

**Review by manojasarsa — APPROVED** [review]
LGTM

**Review by aayushjain-code — COMMENTED** [review]
you can fix the height of your banner for desktop views to fit screen.

**Review by aayushjain-code — APPROVED** [review]

**Review by Mahi24-prog — COMMENTED** [review]
Looks good

**Pull request merged**
